language: python
python:
  - "3.6"
cache: pip
install:
  - pip install .
  - pip install opencv-contrib-python
  - pip install --upgrade pytest
  - pip install pytest pytest-cov
  - pip install codecov
script:
  - pytest --cov=vidstab tests/
after_success:
  - codecov -t 522baa9a-6d29-4939-a238-2150213fbf03
