language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -e git+https://github.com/AdamSpannbauer/python_video_stab.git#egg=vidstab[cv2]
  - pip install --user codecov
script:
  - pytest
after_success:
  - codecov
