theme: jekyll-theme-leap-day
title: vidstab
logo: https://github.com/AdamSpannbauer/python_video_stab/blob/master/readme/vidstab_logo.png?raw=true
show_downloads: true
google_analytics: UA-93461459-1
